import type { NextPage } from 'next'
import Head from 'next/head'
import Script from 'next/script'
import Image from 'next/image'
import idiv from '../assets/img/idiv.jpg';
import BlogCard from '../components/BlogCard/BlogCard'
import LatBlog from '../components/BlogCard/LatBlog'
import HomeTitle from '../components/Title/HomeTitle'


const Home: NextPage = () => {
  return (
    <div className=''>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='true'/>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@500;600;700;800;900&display=swap" rel="stylesheet"></link>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet"></link>
        
        
      </Head>

      <main className='w-screen flex flex-col justify-center items-center gap-y-10 md:pt-12 lg:pt-16'>
        <HomeTitle/>
        <div className='blogs md:w-10/12 lg:w-9/12 gap-y-3'>
          <div className='h-96'>
            <LatBlog/>
          </div>
          <div className='grid grid-cols-2 gap-7 my-4'>
            <BlogCard/>
            <BlogCard/>
            <BlogCard/>
            <BlogCard/>
          </div>
        </div>



      </main>


    </div>
  )
}

export default Home
